trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/**
variables:
- group: epicbook-infra-secrets

stages:
- stage: Terraform
  displayName: Provision Infrastructure
  jobs:
  - job: Terraform_Apply
    displayName: Terraform Apply
    pool:
      name: self-hosted-agent-pool

    steps:
    - checkout: self

    - task: DownloadSecureFile@1
      name: download_ssh_key
      inputs:
        secureFile: id_rsa.pub

    - script: |
        mkdir -p ~/.ssh
        cp "$(download_ssh_key.secureFilePath)" ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub #id_ed25519
        ls -al ~/.ssh
      displayName: Prepare SSH Public Key

    - task: AzureCLI@2
      displayName: Terraform Init Plan Apply
      inputs:
        azureSubscription: epicbook-connect
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(System.DefaultWorkingDirectory)
        inlineScript: |
          terraform version
          terraform init -input=false
          terraform plan -input=false \
            -var-file="terraform.tfvars" \
            -var="ssh_public_key=~/.ssh/id_rsa.pub" \
            -var="db_admin_password=$(db_admin_password)" \
            -out=tfplan
          terraform apply -input=false -auto-approve tfplan
          echo "##vso[task.setvariable variable=app_public_ip;isOutput=true]$(terraform output -raw app_public_ip)"
          echo "##vso[task.setvariable variable=mysql_fqdn;isOutput=true]$(terraform output -raw mysql_fqdn)"
      name: terraform_apply

    - script: |
        echo "Application IP: $(terraform_apply.app_public_ip)"
        echo "MySQL FQDN: $(terraform_apply.mysql_fqdn)"
      displayName: Publish Terraform Outputs
